version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      # Каноничный DSN для SQLAlchemy/SQLModel (самый совместимый)
      DATABASE_URL: postgresql://postgres:password@db:5432/appdb
      # Для формирования short_url в JSON
      BASE_URL: http://localhost:8080
      # В проде у тебя Nginx слушает 80 (Render тоже любит 80)
      PORT: "80"
      FLASK_ENV: development
    ports:
      # Снаружи 8080 (удобно локально), внутри контейнера 80 (nginx)
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: